#!/bin/bash
R="\033[1;31m"
G="\033[1;32m"
Y="\033[1;33m"
PU="\033[1;34m"
PI="\033[1;35m"
B="\033[1;36m"
W="\033[1;37m"
BL="\033[1;30m"
Purple="\e[38;5;93m"
Teal="\e[38;5;37m"
Pink="\e[38;5;206m"
Gold="\e[38;5;220m"
DarkGreen="\e[38;5;28m"
SkyBlue="\e[38;5;111m"

show_help() {
    echo -e "\n${SkyBlue}Usage: ${Gold}linux-distro ${Pink}[OPTIONS]\n"
    echo -e "${Purple}Options:\n"
    echo -e "\t  ${G}--version     ${W}Show version information"
    echo -e "\t  ${G}--help        ${W}Show this help message"
    echo -e "\t  ${G}-F 	        ${W}Follow Dark-Legends\n\n"
}

banner() {
echo -e "\033[1;31m"
echo -e "\t _|        _|_|_|  _|      _|  _|    _|  _|      _|  "
echo -e "\t _|          _|    _|_|    _|  _|    _|    _|  _|    "
echo -e "\t _|          _|    _|  _|  _|  _|    _|      _|      "
echo -e "\t _|          _|    _|    _|_|  _|    _|    _|  _|    "
echo -e "\t _|_|_|_|  _|_|_|  _|      _|    _|_|    _|      _|  "
for ((i=1; i<=4; i++))
do
echo
done


echo -e "\t _|_|_|    _|_|_|    _|_|_|  _|_|_|_|_|  _|_|_|      _|_|    "
echo -e "\t _|    _|    _|    _|            _|      _|    _|  _|    _|  "
echo -e "\t _|    _|    _|      _|_|        _|      _|_|_|    _|    _| "
echo -e "\t _|    _|    _|          _|      _|      _|    _|  _|    _|"
echo -e "\t _|_|_|    _|_|_|  _|_|_|        _|      _|    _|    _|_| "
echo
}

# Function to display help information
display_help() {
	banner
    for ((i=1; i<=5; i++)) do 
      echo 
    done
    echo -e "\t\a${W}Tool Usage\n"
    echo -e "\t${G}How To ${W}Start ${Purple}Linux-Distro ${R}Command\n\n\n"
    echo -e "\t${Y}[ ${PI}1 ${Y}] ${G}Two Start Ubuntu type\n"
    echo -e "\t\t${W}ubuntu\n\n"
    echo -e "\t${Y}[ ${PI}2 ${Y}] ${G}Two Start Debian type\n"
    echo -e "\t\t${W}debian\n\n"
    echo -e "\t${Y}[ ${PI}3 ${Y}] ${G}Two Start Alpine type\n"
    echo -e "\t\t${W}alpine\n\n"
    echo -e "\t${Y}[ ${PI}4 ${Y}]  ${G}Two Start Manjaro type\n"
    echo -e "\t\t${W}manjaro-arrch64\n\n"
    echo -e "\t${Y}[ ${PI}5 ${Y}] ${G}Two Start Arch Linux type\n"
    echo -e "\t\t${W}Archlinux\n\n"
    echo -e "\t${Y}[ ${PI}6 ${Y}] ${G}Two Start Opensuse type\n"
    echo -e "\t\t${W}opensuse\n\n"
    echo -e "\t${Y}[ ${PI}7 ${Y}] ${G}Two Start Viod type\n"
    echo -e "\t\t${W}viod\n\n"
    echo -e "\t${Y}[ ${PI}8 ${Y}] ${G}Two Start Pardus type\n"
    echo -e "\t\t${W}pardus\n\n"
    echo -e "\t${Y}[ ${PI}9 ${Y}] ${G}Two Start Fedora type\n"
    echo -e "\t\t${W}fedora\n\n"
    echo -e "\t${Y}[ ${PI}10 ${Y}] ${G}Two Start Kali Linux type\n"
    echo -e "\t\t${W}nethunter\n\n"
    echo -e "\t${Y}[ ${PI}11 ${Y}] ${G}Two Start Deepin Linux type\n"
    echo -e "\t\t${W}Deepin\n\n"
    echo -e "\t${Y}[ ${PI}12 ${Y}] ${G}Two Start Artix Linux type\n"
    echo -e "\t\t${W}Artix\n\n"
} 

# Check if --help
if [ "$1" == "--help" ]; then
    display_help
    exit 0
fi


while [[ $# -gt 0 ]]; do
    case "$1" in
        --version)
            echo -e "${G}Version: 10.0"
            ;;
                -F)
		  clear
                  xdg-open "https://github.com/Dark-Legends/linux-distro-android"
                  ;;
        *)
            echo -e "Error : Invalid option type ${G}$1"
            ;;
    esac
    shift
done

show_help
