#!/bin/bash

R="\033[1;31m"
G="\033[1;32m"
Y="\033[1;33m"
PU="\033[1;34m"
PI="\033[1;35m"
B="\033[1;36m"
W="\033[1;37m"
BL="\033[1;30m"
Purple="\e[38;5;93m"
Teal="\e[38;5;37m"
Pink="\e[38;5;206m"
Gold="\e[38;5;220m"
DarkGreen="\e[38;5;28m"
SkyBlue="\e[38;5;111m"
clear
banner() {
echo -e "\033[1;31m"                                                     
echo -e "\t _|        _|_|_|  _|      _|  _|    _|  _|      _|  "
echo -e "\t _|          _|    _|_|    _|  _|    _|    _|  _|    "
echo -e "\t _|          _|    _|  _|  _|  _|    _|      _|      "
echo -e "\t _|          _|    _|    _|_|  _|    _|    _|  _|    "
echo -e "\t _|_|_|_|  _|_|_|  _|      _|    _|_|    _|      _|  "
for ((i=1; i<=4; i++))
do
echo
done                                                     
  
echo -e "\t _|_|_|    _|_|_|    _|_|_|  _|_|_|_|_|  _|_|_|      _|_|    "
echo -e "\t _|    _|    _|    _|            _|      _|    _|  _|    _|  "
echo -e "\t _|    _|    _|      _|_|        _|      _|_|_|    _|    _| " 
echo -e "\t _|    _|    _|          _|      _|      _|    _|  _|    _|"  
echo -e "\t _|_|_|    _|_|_|  _|_|_|        _|      _|    _|    _|_| "
echo      
}                                                       
banner
	echo -e "\t\t\t\t\t\t\t${Teal}Version 7.O"   
                                                     
for ((i=1; i<=2; i++))
do
echo
done

echo -e "\t\t\t${SkyBlue}Code ${W}By ${Gold}Manjunath"
for ((i=1; i<=2; i++))
do
echo
done
echo -e "\t${PU}[ ${PI}1 ${PU}] ${G}Install Ubuntu Linux\n"
echo -e "\t${PU}[ ${PI}2 ${PU}] ${G}Install Debian Linux\n"
echo -e "\t${PU}[ ${PI}3 ${PU}] ${G}Install Alpine Linux\n"
echo -e "\t${PU}[ ${PI}4 ${PU}] ${G}Install Manjaro-aarch64 Linux\n"
echo -e "\t${PU}[ ${PI}5 ${PU}] ${G}Install Arch Linux\n"
echo -e "\t${PU}[ ${PI}6 ${PU}] ${G}Install OpenSuse Linux\n"
echo -e "\t${PU}[ ${PI}7 ${PU}] ${G}Install Fedora Linux\n"
echo -e "\t${PU}[ ${PI}8 ${PU}] ${G}Install Pardus Linux\n"
echo -e "\t${PU}[ ${PI}9 ${PU}] ${G}Install Viod Linux\n"
echo -e "\t${PU}[ ${PI}10 ${PU}] ${G}Install Kali Linux\n"
echo -e "\t${PU}[ ${PI}11 ${PU}] ${G}Install Artix Linux\n"
echo -e "\t${PU}[ ${PI}12 ${PU}] ${G}Install All Linux Distros In One Click\n"
echo -e "\t${PU}[ ${PI}13 ${PU}] ${G}Remove Distro info\n"
echo -e "\t${PU}[ ${PI}14 ${PU}] ${G}How To Run Linux-distros info\n"
echo -e "\t${PU}[ ${PI}15 ${PU}] ${G}Follow Dark-Legends On Github\n"
echo -e "\t${PU}[ ${PI}16 ${PU}] ${G}Exit\n"
echo -e "\033[1;33m"

read -p "Enter Your Linux Distro : " Use

	if [[ -z "$Use" || ! "$Use" =~ ^[0-9]+$ ]]; then

	echo -e "\t${R}InvalidError : please Enter a valid Linux Distro Number..."
		exit 1
	fi


  if [ $Use -eq 1 ]; then
	clear
	echo -e "\033[1;32m"
	echo
	proot-distro install ubuntu
	touch $PATH/ubuntu
	echo "proot-distro login ubuntu" > $PATH/ubuntu
	chmod +x $PATH/ubuntu
	echo
	echo
  elif [ $Use -eq 2 ]; then
	clear
	echo
	proot-distro install debian
	touch $PATH/debian
	echo "proot-distro login debian" > $PATH/debian
	chmod +x $PATH/debian
	echo
  elif [ $Use -eq 3 ]; then
	clear
	echo
	proot-distro install alpine
	touch $PATH/alpine
	echo "proot-distro login alpine" > $PATH/alpine
	chmod +x $PATH/alpine
	echo
	echo
  elif [ $Use -eq 4 ]; then
	clear
	echo
	proot-distro install manjaro-aarch64
	touch $PATH/manjaro-aarch64
	echo "proot-distro login manjaro-aarch64" > $PATH/manjaro-arrch64
	chmod +x $PATH/manjaro-aarch64
	echo
  elif [ $Use -eq 5 ]; then
	clear
	echo
	proot-distro install archlinux
	touch $PATH/Archlinux
	echo "proot-distro login archlinx" > $PATH/Archlinux
	chmod +x $PATH/Archlinux
	echo
  elif [ $Use -eq 6 ]; then
	clear
	echo
	proot-distro install opensuse
	touch $PATH/opensuse
	echo "proot-distro login opensuse" > $PATH/opensure
	chmod +x $PATH/opensuse
	echo
  elif [ $Use -eq 7 ]; then
	clear
	echo
	proot-distro install fedora
	touch $PATH/fedora
	echo "proot-distro login fedora" > $PATH/fedora
	chmod +x $PATH/fedora
	echo
  elif [ $Use -eq 8 ]; then
	clear
	echo
	proot-distro install pardus
	touch $PATH/pardus
	echo "proot-distro login pardus" > $PATH/pardus
	chmod +x $PATH/pardus
	echo
  elif [ $Use -eq 9 ]; then
	clear
	echo
	proot-distro install void
	touch $PATH/void
	echo "proot-distro login void" > $PATH/void
	chmod +x $PATH/void
	echo
  elif [ $Use -eq 10 ]; then
	termux-setup-storage
	clear
	pkg install wget -y
	wget -O install-nethunter-termux https://offs.ec/2MceZWr
	chmod +x install-nethunter-termux
	./install-nethunter-termux
  elif [ $Use -eq 11 ]; then
	 clear
	 echo
	 proot-distro install artix
	 touch $PATH/Artix
	 echo "proot-distro login artix" > $PATH/Artix
	 chmod +x $PATH/Artix
	 echo 
  elif [ $Use -eq 12 ]; then
	 clear
        echo
        echo -e "\t${G}Start To Install 10 Linux Distro Now" | pv -qL 20
        echo
        echo
        proot-distro install ubuntu
        touch $PATH/ubuntu
        echo "proot-distro login ubuntu" > $PATH/ubuntu
        chmod +x $PATH/ubuntu
        for ((i=1; i<=5; i++))
        do
        echo
        done
        proot-distro install debian
        touch $PATH/debian
        echo "proot-distro login debian" > $PATH/debian
        chmod +x $PATH/debian
        echo
        for ((i=1; i<=5; i++))
        do
        echo
        done
        proot-distro install alpine
        touch $PATH/alpine
        echo "proot-distro login alpine" > $PATH/alpine
        chmod +x $PATH/alpine
        echo
        echo
        for ((i=1; i<=5; i++))
        do
        echo
        done
        proot-distro install manjaro-aarch64
        touch $PATH/manjaro-aarch64
        echo "proot-distro login manjaro-aarch64" > $PATH/manjaro-arrch64
        chmod +x $PATH/manjaro-aarch64
        echo
        for ((i=1; i<=5; i++))
        do
        echo
        done
        proot-distro install archlinux
        touch $PATH/Archlinux
        echo "proot-distro login archlinx" > $PATH/Archlinux
        chmod +x $PATH/Archlinux
        echo
        for ((i=1; i<=5; i++))
        do
        echo
        done
        echo
        proot-distro install opensuse
        touch $PATH/opensuse
        echo "proot-distro login opensuse" > $PATH/opensure
        chmod +x $PATH/opensuse
        echo
        for ((i=1; i<=5; i++))
        do
        echo
        done
        proot-distro install void
        touch $PATH/void
        echo "proot-distro login void" > $PATH/void
        chmod +x $PATH/void
        for ((i=1; i<=5; i++))
        do
        echo
        done
        proot-distro install pardus
        touch $PATH/pardus
        echo "proot-distro login pardus" > $PATH/pardus
        chmod +x $PATH/pardus
        for ((i=1; i<=5; i++))
        do
        echo
        done
        termux-setup-storage
        pkg install wget -y
        wget -O install-nethunter-termux https://offs.ec/2MceZWr
        chmod +x install-nethunter-termux
        for ((i=1; i<=5; i++))
        do
        echo
        done
        echo
        proot-distro install fedora
        touch $PATH/fedora
        echo "proot-distro login fedora" > $PATH/fedora
        chmod +x $PATH/fedora
        echo
	for ((i=1; i<=5; i++))
	do
	echo
	done
	proot-distro install artix
	touch $PATH/Artix
	echo "proot-distro login artix" > $PATH/Artix
	chmod +x $PATH/Artix
	echo
	echo -e "\a${G}Successfully Installed\n"
  elif [ $Use -eq 13 ]; then
 	clear 
	banner
	bash .remove-distro 
  elif [ $Use -eq 14 ]; then
	bash linux-distro --help
  elif [ $Use -eq 15 ]; then
	termux-open https://github.com/Dark-Legends/linux-distro-android.git
  elif [ $Use == 16 ]; then
	 exit 0
fi
