#!/bin/bash

R="\033[1;31m"
G="\033[1;32m"
Y="\033[1;33m"
PU="\033[1;34m"
PI="\033[1;35m"
B="\033[1;36m"
W="\033[1;37m"
BL="\033[1;30m"
for ((i=1; i<=3; i++))
do
echo
done
echo -e "\tCode By Manjunath"
echo
echo
echo -e "\t${BL}[ ${G}1 ${BL}] ${R}Remove ${W}Ubuntu linux"
echo
echo -e "\t${BL}[ ${G}2 ${BL}] ${R}Remove ${W}Debian linux"
echo
echo -e "\t${BL}[ ${G}3 ${BL}] ${R}Remove ${W}Alpine linux"
echo
echo -e "\t${BL}[ ${G}4 ${BL}] ${R}Remove ${W}Manjaro-aarch64 linux"
echo
echo -e "\t${BL}[ ${G}5 ${BL}] ${R}Remove ${W}Arch linux"
echo
echo -e "\t${BL}[ ${G}6 ${BL}] ${R}Remove ${W}OpenSuse linux"
echo
echo -e "\t${BL}[ ${G}7 ${BL}] ${R}Remove ${W}Fedora linux"
echo
echo -e "\t${BL}[ ${G}8 ${BL}] ${R}Remove ${W}Pardus linux"
echo
echo -e "\t${BL}[ ${G}9 ${BL}] ${R}Remove ${W}Viod linux"
echo
echo -e "\t${BL}[ ${G}10 ${BL}] ${R}Remove ${W}Kali linux"
echo
echo -e "\t${BL}[ ${G}11 ${BL}] ${R}Remove The ${Y}All ${W}Linux Distro"
echo
echo -e "\t${BL}[ ${G}0 ${BL}] ${PI}Go-back"
echo
echo -e "\033[1;36m"
read -p "Enter The Linux Distro To Delete : " Re
echo

   if [[ -z "$Re" || ! "$Re" =~ ^[0-9]+$ ]]; then
echo -e "\t${R}InvalidError : please Enter a valid Linux Distro Number..."
                exit 1
    fi

 if [ $Re -eq 1 ]; then
		clear
		echo
		proot-distro remove ubuntu
		echo
		rm $PATH/ubuntu
		sleep 1
	echo -e "\t${G}Your ubuntu Distro ${R}Delete"
 elif [ $Re -eq 2 ]; then
		clear
		echo
		proot-distro remove debian
		echo
		rm $PATH/debian
		sleep 1
	echo -e "\t${G}Your Debian Distro ${R}Delete"
 elif [ $Re -eq 3 ]; then
		clear
		echo
		proot-distro remove alpine
		echo
		rm $PATH/alpine
		sleep 1
	echo -e "\t${G}Your Alpine Debian Distro ${R}Delete"
  elif [ $Re -eq 4 ]; then
		clear
		echo
		proot-distro remove manjaro-aarch64
		echo
		rm $PATH/manjaro-arrch64
		sleep 1
	echo -e "\t${G}Your Manjaro-arrch64 Disrto ${R}Delete"
  elif [ $Re -eq 5 ]; then
		clear
		echo
		proot-distro remove archlinux
		echo
		rm $PATH/Archlinux
		sleep 1
	echo -e "\t${G}Your Archlinux Disrto ${R}Delete"
  elif [ $Re -eq 6 ]; then
		clear
		echo
		proot-distro remove opensuse
		echo
		rm $PATH/opensuse
		sleep 1
	echo -e "\t${G}Your Opensuse Disrto ${G}Delete"
  elif [ $Re -eq 7 ]; then
		clear
		echo
		proot-distro remove fedora
		rm $PATH/fedora
		sleep 1
	echo -e "\t${G}Your Fedora Distro ${R}Delete"
  elif [ $Re -eq 8 ]; then
		clear
		echo
		proot-distro remove pardus
		rm $PATH/pardus
		sleep 1
	echo -e ?"\t${G}Your Pardus Distro ${R}Delete"
  elif [ $Re -eq 9 ]; then
		clear
		echo
		proot-distro remove viod
		rm $PATH/void
		sleep 1
	echo -e "\t${G}Your viod Distro ${R}Delete"
  elif [ $Re -eq 10 ]; then
		clear
		cd ..
		echo
		rm -rf kali-arm64
		sleep 1
	echo -e "\t${G}Your Kali Distro ${R}Delete"
  elif [ $Re -eq 11 ]; then
		banner
		echo
                proot-distro remove ubuntu
                echo
                rm $PATH/ubuntu
                sleep 1
		echo
                proot-distro remove debian
                echo
                rm $PATH/debian
                sleep 1
		echo
                proot-distro remove alpine
                echo
                rm $PATH/alpine
                sleep 1
		echo
                proot-distro remove manjaro-aarch64
                echo
                rm $PATH/manjaro-arrch64
                sleep 1
		echo
                proot-distro remove archlinux
                echo
                rm $PATH/Archlinux
                sleep 1
		echo
                proot-distro remove opensuse
                echo
                rm $PATH/opensuse
                sleep 1
		echo
                proot-distro remove fedora
                rm $PATH/fedora
                sleep 1
		echo
                proot-distro remove pardus
                rm $PATH/pardus
                sleep 1
		echo
                proot-distro remove viod
                rm $PATH/void
                sleep 1
		cd ..
                echo
                rm -rf kali-arm64
                sleep 1
  elif [ $Re -eq 0 ]; then
		clear
		bash Linux-distro
fi
